### ISSUE TITLE
Reading in JENDL endf files

### ISSUE THREAD

**Issue by Shimwell** [openmc-dev/openmc#1161]
Dear all

I am trying to convert JENDL (which is  in endf format) into h5 format for use in OpenMC

I have downloaded the [library](https://wwwndc.jaea.go.jp/ftpnd/ftp/JENDL/jendl40-up-0k_20160106.tar.gz) and am running the `openmc.data.IncidentNeutron.from_endf` method on the extracted files.

This appears to cause an error with some files (for example 'Ag109.t000'). I believe this is because line 402 in openmc/data/endf.py tries to read in the lines for MF and MT assignment numbers but this causes an error when the line read in is like this ...
`  JENDL-4.0 Ag109_u1 pointwise at 0K                                 0         0`

openmc/data/endf.py trys to read in the above line from the endf file assign the characters 70:72 as an integer but in this case the characters are '   ' so this causes an error.

Changing the endf.py to something like this appears to work but perhaps it is not be best solution

```
        # Determine MAT number for this evaluation
        MF = 0
        while MF == 0:
            position = fh.tell()
            line = fh.readline()
            try:
                MF = int(line[70:72])
            except:
                pass # The first line does not contain and int at positions 70:72, MF remains equal to 0
        self.material = int(line[66:70])
        fh.seek(position)
```

**Comment by paulromano** [comment]
`<rant>`
I've run into this problem and many others like it countless times. The moral of the story is that data evaluators don't seem to pay much attention to the ENDF-6 format because they continually invent new ways to not follow it. This is a pretty common one: the first line of an ENDF file, known as `TPID`. The ENDF-6 manual has this to say about `TPID`:

> For a TPID record, MAT contains the tape number NTAPE, and MF and MT are both zero.

What you're finding is that it chokes because OpenMC is looking for zeros and the file doesn't have them. OpenMC expects that if you pass it an ENDF file, it is properly formatted. I've put in fudges over time to get files to work, but at some point I just give up :) Please report as a 
`</rant>`

Ok, now if you really want to process an ENDF file to HDF5, you should probably be using `IncidentNeutron.from_njoy()` which will run NJOY under the hood for you. `from_endf()` is cool if you want to see what is really in the ENDF file, but it doesn't allow you to process it into pointwise data that the MC solver actually needs.

**Comment by Shimwell** [comment]
Great I shall give the `from_njoy()` a go. 

Perhaps `from_endf()` should still be able to handle endf files with TPID records so I happy to put in a PR for that small change if you like

Otherwise this issue can be closed and I shall use `from_njoy()` for my needs, as I want to include some extra MT numbers as well as seeing what is inside the file.

Perhaps another option is the [njoy/ENDFTK](https://github.com/njoy/ENDFtk) but perhaps it is not quite ready.

Thanks @paulromano

**Comment by paulromano** [comment]
To be clear, it can handle files with TPID records fine, just not ones that don't follow the correct format. In any event, I can put in a workaround. It seems sufficient to just skip the first line in the file.

**Comment by Shimwell** [comment]
Thanks Paul

**Comment by paulromano** [comment]
@Shimwell Your JENDL files should work fine on the develop branch now. Let me know if you are still seeing any issues with those files.
