### ISSUE TITLE
Account for capture branching ratios in depletion chains

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1237]
This is mentioned in #977 and was originally discussed [here](https://github.com/mit-crpg/opendeplete/issues/33), but I thought it deserves its own issue. The depletion chains that we have generated so far (full ENDF/B-VII.1, CASL chain) don't have any capture branching ratios. This leads to wrong isotopic concentrations for higher actinides (since we miss Am241 and Am243 capture branching) as well as Ag110m.

Upon looking at our deplete module, there is nothing that inherently stops us from having multiple `<reaction>`s with the same type but different targets. In fact, we already have the data structures set up to take a branching ratio on a reaction.

The main questions are:
- What branching ratios to use? For starters, we can use the values that [Serpent uses](http://serpent.vtt.fi/mediawiki/index.php/Default_isomeric_branching_ratios). These were computed in a typical LWR spectrum, but generally the spectral effects will probably be small.
- In a reduced chain (e.g., our CASL 255 nuclide chain), what should we do when the metastable product from capture is not in the chain already? The easiest thing to do is to just have it still go to ground, but this will definitely be wrong in some cases. To be more accurate, we should really look at the decay files for the missing product to see what would have happened and adjust the target accordingly.

**Comment by drewejohnson** [comment]
I've got an in progress branch for this fix that I wanted to introduce and discuss here.

First, the `Chain` will be able to load in new branching ratios with a nested dictionary
```
>>> c = openmc.deplete.Chain.from_xml(chain_file)
>>> new_br = {"Am241": {"Am242": 0.9, "Am242_m1": 0.1}, ... }
>>> c.set_capture_branches(new_br)
```
A companion method `get_capture_branches` retrieves a similar dictionary.

The setter overwrites existing capture branches, mainly because the `ReactionTuples` are immutable. The `Q` value is assumed constant across branches. I haven't found anything in literature to say this is a bad assumption, but my gut says the Q value should be reduced by the energy of the metastable state. 

To the question of what branching ratios to use, one route would be to run a transport simulation prior to burnup, could be a model assembly for large problems, to get a more representative spectrum. This spectrum could be used to produce a set of branching ratios that reflect the problem better than those provided by SERPENT using an LWR spectrum.

The SERPENT wiki provides an example of how one could do that, reproduced here
```
% --- Detector material:
mat Am241 1.0 95241.09c 1.0
% --- Detector: (reaction rates using spectrum in material "fuel")
det 1 dm fuel
dr 102 Am241 dr 102g  Am241 dr 102m  Am241
```
This will produce one-group cross sections for the total capture reaction, capture to ground, and capture to metastable for Am241. The branching ratios would then be the ratio to total capture cross section, `102g / 102`, `102m / 102`. With this, one could create a new branching ratio map given a better approximation of the spectrum.

The more complicated but more accurate way would be to directly compute [potentially region specific] branching ratios directly in the transport simulation. To do this, we would have to pass tally data for reaction rates and these branching ratios into the routine for making the depletion matrix. We may have to do similar modifications to pass fission yield data, specifically 3-group flux ratios, to resolve #1263

**Comment by drewejohnson** [comment]
Some [possibly] related information. SERPENT allows users to pass libraries for branching ratios: [`set bralib`](http://serpent.vtt.fi/mediawiki/index.php/Input_syntax_manual#set_bralib). These libraries can be the ENDF/B-7.1 files distributed with `openmc` through the `download-xs.sh` script, and they instruct SERPENT to use energy dependent branching ratios for specific reactions. There is also a JEFF 3.1 activation file that can be obtained through the wiki.

From reading the output, SERPENT appears to use these branching ratios for all reactions that have some energy dependency. These include:

- MT 102: (n, gamma)
- MT 108: (n, 2alpha)
- MT 16: (n, 2n)
- MT 17: (n, 3n)
- MT 41: (n, 2np)
- MT 4: total inelastic scattering

**Comment by paulromano** [comment]
@drewejohnson I think we can close this issue at this point now that we have a method for setting branching ratios generally, and depletion chains with branching ratios distributed at https://openmc.org.
