### ISSUE TITLE
Account for indirect energy release in depletion power normalization

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1238]
To determine reaction rates to deplete materials, the method we use now is to

1. Take the sum of the fission rate of each nuclide multiplied by the Q value for fission to get an "observed power".
2. Renormalize the reaction rates based on the ratio of the user-specified power to the observed power.

Notably, the Q value that is used right now is whatever is listed in MF=3 in the ENDF file, which corresponds the recoverable energy release (total energy release from fission minus neutrinos). It does not account for indirect energy release, namely the energy released from (n,gamma) reactions, which can account for over 5 MeV of energy release per fission event.

Since we are not including indirect energy release, the normalized reaction rates tend to be too high -- with a lower Q, you need more fission reactions to reach the same power level. This results in OpenMC depleting too fast.

The simple fix is to simply increase the Q values in the depletion chain to account for the indirect energy release. This is effectively what Serpent has traditionally done; the heating value for U235 was [set to 202.27 MeV by default](http://serpent.vtt.fi/mediawiki/index.php/Input_syntax_manual#set_U235H). I understand they have a [new energy deposition treatment](https://doi.org/10.1016/j.anucene.2019.02.003) so more recent versions might not use the constant heating values for depletion power normalization.

Longer-term, we ought to provide some options for how to do power normalization rather than just brute-force, arbitrary changes to the Q values used in the depletion chain.

Thanks to @pshriwise for helping to remind us of this through his comparisons to Serpent.

**Comment by liangjg** [comment]
The [Serpent paper](https://doi.org/10.1016/j.anucene.2019.02.003) summarized a series of "energy deposition modes", with increasing accuracy and complexity:
- constant Q_fiss: all fission Q being scaled by the ratio H_U235/Q_{fiss,U235} where H_U235 is 202.27 MeV by default and can be specified. (this can be done easily and already tested in the recent work by @jiankai. I can submit a PR later for this)
- flux-dependent Q_fiss from MT458: energy deposition is tallied with MT458 components (`fission_energy_release` data in the library), and the user can specify a constant capture energy per fission for all nuclides. (not accurate and not recommended)
- capture heating with KREMA: neutron heating rate due to reactions other than fission is calculated
using KERMA coefficients. (this is more accurate and efficient, but it needs non-fission KERMA, photon energy is deposited in fission sites)
- coupled neutron-photon transport: most accurate. (this is almost done with the adding of neutron and photon heating tally #1191 and #1203, but this is most computationally expensive)
@paulromano

**Comment by paulromano** [comment]
Thanks for outlining that @liangjg. Why is flux-dependent Q_fiss less accurate than constant Q_fiss?

**Comment by liangjg** [comment]
@paulromano the accuracy of the second mode actually depends on the user-specified capture q. In the tests the paper shows, the q was set to 0 so the energy deposition is always too low. If the user is able to set correct capture Qs which should be different across nuclides, this mode can be accurate as well.

![image](https://user-images.githubusercontent.com/3030455/58348704-5ec45a80-7e2f-11e9-8f42-e7805b9f14a3.png)

**Comment by paulromano** [comment]
Ah, well of course if you have no indirect then it's wrong :) The method that Serpent chooses feels very ad hoc to me. Do you know of any justification as to why one should scale Q_recoverable by the ratio of U235 heating to U235 Q? To me it seems the indirect energy release for fission of a given nuclide would be more related to the number of neutrons emitted per fission -- if it emits more neutrons, it has a higher chance of causing (n,gamma) elsewhere.

**Comment by liangjg** [comment]
So you are proposing Q'_i = Q_i + nu_i*(H_U235 - Q_U235)/nu_U235? I guess it worths a try, but it needs a way to get the effective nu_i, the number of neutrons emitted per fission.
Another way to approximate the energy deposition is Q = Q_f*RR_fiss + Q_c*RR_capture, where Q_c is the capture recoverable energy which can be specified per actinide (around 5 MeV). The benefit is no additional tally is needed. Seems Scale is using this one?

**Comment by paulromano** [comment]
I'm not necessarily proposing that we use that formulation -- just pointing out that I've never understood the basis for the choice that Serpent made. Applying the Q value for capture makes sense except that we'll miss all the capture reactions in non-fuel materials. According to the Serpent paper, that looks to be about 3-5% of all energy.

**Comment by rtuom** [comment]
Hi guys,

a colleague of mine linked me this discussion and I wanted to comment a bit about the energy deposition models I implemented to Serpent. First of all, I agree that the scaling does not make that much sense. I left it there for backwards compatibility. The additional energy release in capture reactions should be dependent on the number of neutrons emitted per fission. Something like this is used for example in CASMO-5 ([See this paper](https://www.studsvik.com/SharepointFiles/CASMO-5%20Energy%20Release%20per%20Fission%20Model.pdf)). I could have implemented something like this for energy deposition mode 1 which calculates the fission energy deposition using MT 458 data. However, one still has to know the additional energy deposition due to capture per fission neutron. Moreover, with KERMA coefficients the additional energy release is accounted for automatically with a very small increase in the required calculation time.

Best, 
Riku

**Comment by paulromano** [comment]
@rtuom Thanks for chiming in and for mentioning the CASMO paper!

**Comment by drewejohnson** [comment]
@liangjg did you end up submitting that PR for the scaled fission power? I am interested in picking that up if you are willing to point me towards an in-process revision.
