### ISSUE TITLE
Two failures in IncidentNeutron.from_*

### ISSUE THREAD

**Issue by liangjg** [openmc-dev/openmc#1382]
1. No redundant reactions in HDF5
``` python
# get neutron data from ace or njoy
# nuc = openmc.data.IncidentNeutron.from_ace("./endf71x/H/1001.710nc", "mcnp")
nuc = openmc.data.IncidentNeutron.from_njoy("./endf-b-vii.1/neutrons/n-001_H_001.endf")
nuc.export_to_hdf5("H1.h5")
nuc2 = openmc.data.IncidentNeutron.from_hdf5("H1.h5")
nuc2[1]
KeyError: 'No reaction with MT=1.'
```
This is because (some) redundant reactions are not written into HDF5 in `export_to_hdf5` while since #1219 , the building of redundant reactions in HDF5 isremoved. Not sure if this behavior is intended. If not, we may change to export all redundant reactions in HDF5.

2. Reading ace fails for B10 from ENDF/B VIII.0
```python
nuc = openmc.data.IncidentNeutron.from_njoy("/home/jingang/nucdata/endf-b-viii.0/neutrons/n-005_B_010.endf")
AssertionError： assert xss.size == nxs[1] + 1
```
- B10 is currently the only nuclide I found which has such issue
- Maybe a bug of njoy though it generates ace file successfully
- In the generated ace file, the `xss` array is longer than what `nxs[1]` indicates.

**Comment by paulromano** [comment]
My philosophy for redundant reactions is to only write those that will actually be needed by the transport solver. We always recreate the total xs, so no need to store that one. Yes, you do get MT=1 when you call `from_ace` or `from_njoy` but that is because the ACE file already has it there. I'm inclined to say "wont fix" for the particular behavior you're describing unless I hear a compelling argument as to why it should be there.

For the second one, I've known about this since before ENDF/B-VIII.0 was even released and [filed an issue](https://github.com/njoy/NJOY2016/issues/50) with NJOY back in Jan 2018. So far it seems to have been ignored because they ran it "through MCNP and don't get any noticeable problems". Feel free to make a comment on the issue there or at least give it a :+1:. Also, note that I have a fix for this when [converting lib80x](https://github.com/openmc-dev/data/blob/master/convert_lib80x.py) so you can use that same logic if you need.

**Comment by liangjg** [comment]
@paulromano I agree to store redundant reactions in HDF5 is not an ideal way. But are you felling "no total xs" behavior is kind of imperfection in the OpenMC Python API?
Anyway, we can either:
1. leave it, let users create missing redundant reactions by themselves, like
``` python
total_xs = nuc._get_redundant_reaction(1, nuc.get_reaction_components(1))
```
2. or, try to recreate the total xs when requested, like, 
``` diff
class IncidentNeutron(EqualityMixin):

     def __getitem__(self, mt):
         if mt in self.reactions:
             return self.reactions[mt]
         else:
-            raise KeyError('No reaction with MT={}.'.format(mt))
+            # Recreate redundant cross sections
+            mts = self.get_reaction_components(mt)
+            if len(mts) > 0:
+                return self._get_redundant_reaction(mt, mts)
+            else:
+                raise KeyError('No reaction with MT={}.'.format(mt))

**Comment by liangjg** [comment]
@paulromano and thanks for explaining the B10 issue. I just gave a 👍 on [the issue](https://github.com/njoy/NJOY2016/issues/50) 😀

**Comment by paulromano** [comment]
@liangjg not a bad idea to recreate total xs when requested. Do you want to submit a PR to that effect?
