### ISSUE TITLE
(X,Y,Z)Plane superclass attributes are inconsistent with Ax + By + Cz = D representation

### ISSUE THREAD

**Issue by eepeterson** [openmc-dev/openmc#1475]
In working on PR #1474 I realized that (X,Y,Z)Planes have attributes a=1, b=0, c=0, d=0 which is not consistent with the representation of a Plane in openmc. In order to clean up the inheritance structure and make it possible to compare planes to determine if a Plane is an (X,Y,Z)Plane I would suggest modifying the constructors for (X,Y,Z)Planes to be consistent i.e. for a YPlane with y0=5 setting a=0, b=1, c=0, d=5 and altering the behavior of YPlane.y0 to return YPlane.d. I would also suggest similar changes to the Cylinder classes this would allow for the new Cylinder.from_points class method to return a Cylinder object rather than a Quadric option which would clean up the abstraction a bit. Ultimately where this seems to be leading is everything being a subclass of Quadric effectively as this  is how the geometrical hierarchy actually behaves. I'm not sure what the best approach is here whether it is to have each shape inherit from Surface as well as another class representing the dimensionality i.e. Linear for Planes, Quadric for Cylinders, Spheres, Ellipsoids, etc and perhaps a Quartic surface to represent a Torus? I'm wondering what @paulromano @smharper @pshriwise think if they have a second.

**Comment by paulromano** [comment]
I completely agree with you with respect to the "canonical" representation of planes. Regardless of the class, they all should just store the a,b,c,d coefficients and return the correct value for properties (as you say: YPlane.y0 just returns d).

For cylinders, what would be the underlying representation? Right now as you know we only store the center (x0, y0, z0) and the radius. That wouldn't permit representing an arbitrarily-oriented cylinder, which is why the current [`cylinder_from_points` function](https://docs.openmc.org/en/latest/pythonapi/generated/openmc.model.cylinder_from_points.html#openmc.model.cylinder_from_points) returns a `Quadric` instance.

**Comment by eepeterson** [comment]
I was thinking for cylinders we could add a unit vector (u, v, w) that represents the axis. 

I've been struggling trying to implement a good class hierarchy during PR #1474 which I just closed. The main problem I keep running into is guaranteeing a consistent internal representation without implementing a bunch of side-effects in property setters, which would get messy and is probably poor form.

What this has actually led me to is to the following thought process (tldr: `XPlane` etc should not inherit from `Plane`, but from `PlaneMeta` as should _all_ types of planes. The same is true for all quadric shapes. All cylinders (x,y,z) should inherit from `QuadricMeta` rather than `Cylinder`. This will reduce code duplication, prevent internal state inconsistencies, and make adding new geometry classes even easier as explained below):

1.) Add a `Plane(Mixin/Meta)` class which stores no attributes, but defines all the operations for order 1 surfaces like `translate`, `rotate`, `periodic_surface` setter, `to_xml_element` and two abstract methods `_to_base_coeffs` and `_from_base_coeffs`
2.) These last two abstract methods are the important ones, which must be overridden in each subclass to map the independent coefficients of the sub geometry to the general form (i.e. takes x0 for an `XPlane` and returns (1, 0, 0, x0). If we do this, then in the translate and rotate methods we simply call _to_base_coeffs at the beginning, perform the transformation, and then transform back.
3.) This actually means that `Plane`, `XPlane`, `YPlane`, and `ZPlane` are subclasses of `PlaneMeta` rather than Plane, which is nice because then we don't have to store the generalized coefficients anywhere and we don't need to worry about inconsistent internal states - just compute them on the fly when they are needed for a transformation. 
4.) This methodology would be easily generalizable to `QuadricMeta`, `QuarticMeta`, etc
5.) You could then pretty easily implement `__new__` in the metaclass to intercept any object creation from a rotation (or a bunch of zeros) and return the simplest version

Then a class for `Cylinder` would look something like `class Cylinder(Surface, QuadricMeta)` and only have to define the minimum set of independent coefficients that fully describes the surface and the mapping to and from the general quadric coefficients which can be hidden from the user. If we are going to have distinct classes for all Cylinders (arbitrary, X, Y, Z) then I think it makes the implementation cleaner if the X, Y, Z are not subclasses of the general case, just the metaclass. If we really want, we could register them using  `__subclasshook__` so they appear as Cylinder instances, but don't inherit from Cylinder.

**Comment by paulromano** [comment]
@eepeterson All good points. I don't see any major downsides to what you're proposing, and quite a few upsides. I do think we would want, e.g., `isinstance(xplane, Plane)` where `xplane` is an instance of `XPlane` to be True since a user could reasonably expect to rely on such behavior; like you said, a subclass hook would allow that even if there is no class inheritance.

For the meta/mixin classes, would it be sufficient to subclass [abc.ABC](https://docs.python.org/3/library/abc.html#abc.ABC)?

**Comment by eepeterson** [comment]
@paulromano Yes, it should be.

**Comment by eepeterson** [comment]
closed per PR #1483
