### ISSUE TITLE
It is wrong to set mpicxx while using cmake for parallel build.

### ISSUE THREAD

**Issue by tuanhtrng** [openmc-dev/openmc#1571]
> This is completely, utterly wrong!

https://cmake.org/pipermail/cmake/2011-June/045037.html

**Comment by paulromano** [comment]
The comment in that post about being "completely, utterly wrong" most likely refers to manually setting CMAKE_CXX_COMPILER within CMakeLists.txt, which I would agree is completely wrong. However, using the CC/CXX environment variables, as is suggested in our user's manual, seems to work quite well in practice. Can you elaborate on what would go wrong with this approach versus using FindMPI from CMake?

**Comment by tuanhtrng** [comment]
Firstly, FindMPI is more robust. Looking at the [source](https://github.com/Kitware/CMake/blob/master/Modules/FindMPI.cmake#L99), you might find that it covers more than just the wrapper case that OpenMC implements.

Secondly, OpenMC would be more modular with it. I am thinking of using OpenMC as a submodule but its use of wrapper would make me compile everything else with mpi.

Why did you not want to use FindMPI?

**Comment by paulromano** [comment]
It's been a while since that was all put together, but I think mostly this approach was chosen for simplicity -- there is never a question of where/how CMake will find MPI. And, as I mentioned earlier, we've never had a problem doing it that way.

I understand the argument about using OpenMC as a dependency. In other cases where we've had this situation, it wouldn't have made sense to use a different compiler for the other components so using a single `CC/CXX` environment variable was fine. And when there are components that don't use MPI, the wrappers generally don't hurt (since they just `-I` and `-l` flags). Would this cause problems in your case though?

I'm stretched thin and don't have time to try to implement this change to CMakeLists.txt, but if you are interested in making a contribution, we would welcome a pull request!

**Comment by tuanhtrng** [comment]
> And when there are components that don't use MPI, the wrappers generally don't hurt (since they just -I and -l flags).

It is nice to have everything, including the building process, works as intended.

> Would this cause problems in your case though?

These are my initial thoughts after reading the manual. I had openmc compiled as a standalone but will try it as a dependency soon. It might work fine since the other modules use FindMPI and we know the CC/CXX mpi wraper will just work.

> I'm stretched thin and don't have time to try to implement this change to CMakeLists.txt, but if you are interested in making a contribution, we would welcome a pull request!

I will make a pull request when it is ready.
