### ISSUE TITLE
An obvious difference between openmc and the reference result

### ISSUE THREAD

**Issue by D-Benjamin** [openmc-dev/openmc#1574]
Hi all,
    Recently, I obtained the decay constants and the delayed neutron yield of Molten Slat Fast Reactor by openmc. However,  An obvious difference appears between openmc and the reference result. Following is the reference result ([TUDelft](https://d1rkab7tlqy5f1.cloudfront.net/TNW/Afdelingen/Radiation%20Science%20and%20Technology/Research%20Groups/RPNM/Publications/MSc_Erik_van_der_Linden.pdf)):

![图片](https://user-images.githubusercontent.com/45137022/83223038-81a8ed80-a1ac-11ea-842c-b95bc29711c1.png)

The geometry and the fuel composition which are adopted in my model are the same with the reference, the difference is that a continuous-energy Monte Carlo method by OpenMC is adopted by my work, while a 9-energy groups Deterministic method was selected in reference result's work. Following is my result:

**delayed constant**:
![图片](https://user-images.githubusercontent.com/45137022/83223867-91c1cc80-a1ae-11ea-8433-c65d686a0752.png)

**delayed neutron yield**:
![nu](https://user-images.githubusercontent.com/45137022/83223927-bf0e7a80-a1ae-11ea-9d00-bfe2a5a53ee7.png)

It can be seen that an obvious difference of group 3 ~ group 6 appears between openmc and the reference result, especially for group 5 and group 6. Here is my openmc input script: [MC_bm_upload.txt](https://github.com/openmc-dev/openmc/files/4699815/MC_bm_upload.txt)

I'm not sure whether it is a bug or not, any reply will be appreciated!

Best Regards!

**Comment by cjwyett** [comment]
I havn't It would be a good (albeit time consuming) idea to compare these with results from an alternative neutronics package like Serpent or MCNP. 

It is possible that you're more accurate than the reference results. It's hard to confidently model MSR deterministically due to the lack of experimental data from real reactors.

**Comment by D-Benjamin** [comment]
> It would be a good (albeit time consuming) idea to compare these with results from an alternative neutronics package like Serpent or MCNP.
> 
> It is possible that you're more accurate than the reference results. It's hard to confidently model MSR deterministically due to the lack of experimental data from real reactors.

@cjwyett Thank u very much for your advance.

**Comment by paulromano** [comment]
@cjwyett's explanation is right. If you are comparing a Monte Carlo code to a deterministic code, you should not expect exact agreement. A deterministic solution will have errors from:
- cross section generation 
- spatial discretization
- angular discretization
- physics approximations (use of diffusion theory, e.g.)

This is why people usually use a solution by the Monte Carlo method as their reference solution, since it is not subject to any of the discretization errors.
