### ISSUE TITLE
Material.add_elements_from_formula ignores enrichment parameter for U

### ISSUE THREAD

**Issue by cgarta** [openmc-dev/openmc#1600]
Defining a material using add_elements_from_formula method with enrichment in U235 doesn’t work.
uo2.add_elements_from_formula('UO2', enrichment=4.0) and uo2.add_elements_from_formula('UO2') both give the same compositions.

**Comment by Shimwell** [comment]
I realize this is not a solution but it gives a little more detail if you pass "enrichment_target=U" as an argument. It looks like it is trying to enrich U using the normal enrichment strategy for elements with just two isotopes.

This is due to the perhaps logic [here ](https://github.com/openmc-dev/openmc/blob/557385c2bfbda828ebe6dbfd00d579a3c5272850/openmc/material.py#L652-L658)

U is enriched differently to elements with just two isotopes so I guess this is why I missed this earlier. Sorry about that.

Just out of interest does this work for you.

mat1 = openmc.Material()
mat1.add_element('U', percent=1, enrichment=4, enrichment_target='U')

Do people think that Uranium should be enriched when it is specified as a target? Currently it needs to be enrichment_target=None to enrich Uranium which is different to the other elements 

I'm wonder if the thing to fix is in openmc/materials.py add_elements function

I'm wondering if we should change [this line so](https://github.com/openmc-dev/openmc/blob/557385c2bfbda828ebe6dbfd00d579a3c5272850/openmc/material.py#L530) that it is true even if statement when the enrichment_target is set to None or to 'U'

**Comment by drewejohnson** [comment]
This was closed in #1605
