### ISSUE TITLE
KeyError in ResultsList.get_atoms

### ISSUE THREAD

**Issue by pshriwise** [openmc-dev/openmc#1626]
I ran into this one today and have a fix, but I wanted to post here to make sure I'm not just using the interface incorrectly and that my proposed fix is the right idea.

[This block](https://github.com/openmc-dev/openmc/blob/c9120bafbcff2ce8d1bb2261f93193a1828a2ef4/openmc/deplete/results_list.py#L85) in `ResultsList` seems to expect that a given nuclide exists for all timesteps, but that is not likely the case for the majority of nuclides at the initial timestep.

It seems as though the concentrations should be set to zero if the nuclide isn't present in the `Result.nuc_to_ind` mapping.

**Comment by cjwyett** [comment]
> This block in ResultsList seems to expect that a given nuclide exists for all timesteps, but that is not likely the case for the majority of nuclides at the initial timestep.

You are correct; there will be nuclides (e.g. TRUs) that are not present at t=0.

**Comment by drewejohnson** [comment]
For isotopes that don't exist at t=0, they will be added to the problem as trace isotopes with some very small density, set by passing a non-zero `dillute_initial` parameter when initializing an `Operator`. These isotopes are added to the result file at this density for t=0, even though we know their density is really zero. Using the depletion regression test reference file,
```python
>>> import openmc.deplete
>>> r = openmc.deplete.ResultsList.from_hdf5("test_reference.h5")
>>> t, xe = r.get_atoms("1", "Xe135")
>>> xe  # doesn't exist at t=0
array([6.67473282e+08, 3.76986925e+14, 3.68587383e+14, 3.91338675e+14])
```

The `KeyError` is raised if the isotope truly doesn't exist in the data file, per the block you pointed out https://github.com/openmc-dev/openmc/blob/c9120bafbcff2ce8d1bb2261f93193a1828a2ef4/openmc/deplete/results_list.py#L85-L87 due to https://github.com/openmc-dev/openmc/blob/c9120bafbcff2ce8d1bb2261f93193a1828a2ef4/openmc/deplete/results.py#L90-L91 but our trace isotopes exist in this mapping
```python
>>> r[0].nuc_to_ind
OrderedDict([('Cs135', 3),
             ('Gd156', 5),
             ('Gd157', 4),
             ('I135', 0),
             ('U234', 6),
             ('U235', 7),
             ('U238', 8),
             ('Xe135', 1),
             ('Xe136', 2)])
```

**Comment by pshriwise** [comment]
Ah! Ok I see what I was doing wrong now. I was looping over all nuclides with incident neutron data in the `cross_sections.xml` (i.e. `nucs_with_data` when I should've been limiting that to the depletion chain. Got the XML's switched around in my head somehow. My mistake! Thanks @drewejohnson.
