### ISSUE TITLE
Skip reading cross sections when calculating volume

### ISSUE THREAD

**Issue by kingyue737** [openmc-dev/openmc#1662]
When I try to calculate volume of depletable material via "openmc --volume", an error is raised:
```
 Reading settings XML file...
 Reading cross sections XML file...
 Reading materials XML file...
 Reading geometry XML file...
 Reading O16 from /home/yuejin/Cloud/nuclear_data_libraries/endfb71_hdf5/O16.h5
 ERROR: Nuclear data library does not contain cross sections for O16 at or near
        577.000000 K.
```

It's strange that openmc needs to load cross sections in volume mode. Maybe volume mode should be treated like plotting mode which skips reading of continuous-energy cross sections in `read_input_xml`?

https://github.com/openmc-dev/openmc/blob/efc6f5a2141df54c8d9decd0a8a21d2cb10a02d0/src/initialize.cpp#L264-L276

**Comment by paulromano** [comment]
Because the volume calculation mode calculates not only volume but also the total number of atoms of each nuclide, it does end up using some information from when cross sections are loaded. Namely, in order to know the properly normalized atom densities of each nuclide in a material, it needs to know the atomic mass of each nuclide present (which is found from the cross section data).

**Comment by kingyue737** [comment]
Got it! Thanks, @paulromano
