### ISSUE TITLE
Testing issue when using nearest temperature method and large tolerance

### ISSUE THREAD

**Issue by rockfool** [openmc-dev/openmc#1704]
When I tried to test wmp library of endf/b-viii.0 based on vera 2e case, the weird results were found here:
![test_wmp-8 0](https://user-images.githubusercontent.com/2571415/96902179-31377280-1462-11eb-9f13-de049c97b7c5.PNG)
It seems like the issue is caused by incorrect dealing with nearest method with large tolerance, instead of wmp implementation. 
And I tested the library of endf/b0vii.1 to see if there is the same issue, 
![test_wmp-7 1](https://user-images.githubusercontent.com/2571415/96902264-4d3b1400-1462-11eb-8e81-db48fd1f8df5.PNG)

**Comment by paulromano** [comment]
@rockfool Can you elaborate on this? I'm not fully sure how to interpret your results. Can you say what you were expecting to see with the different options and how the observations differ from that?

**Comment by rockfool** [comment]
I mean when I try to use wmp library in the realistic application (i.e., 565K, 749K, 1199K), to minimize the hdf5 data processing, I prefer the data set at only one temperature (i.e., 293.6K). However, in such a case I have to use the option in settings, (method:"nearest", tolerance=1000, multipole="on"). And this case results in an k-effective error as shown in case no. 3 of the first table.

**Comment by paulromano** [comment]
Ok, I think I figured out what the issue is. When the nearest method is in use, we don't actually find the nearest temperature for S(a,b) data but rather the first temperature that is within the tolerance. This means that when you set the tolerance really large, it will always pick the lowest temperature for S(a,b) data. The relevant lines are [here](https://github.com/openmc-dev/openmc/blob/develop/src/thermal.cpp#L156-L161). I'll put in a PR fixing this soon.

**Comment by rockfool** [comment]
Got it, I never check the S(a, b) data. Thanks for your fixing.
