### ISSUE TITLE
OpenMc isotope density to concentration??? 

### ISSUE THREAD

**Issue by hhhnain** [openmc-dev/openmc#1751]
Currently, i'm running simple openmc depletion code and I'm getting the change in number densities overtime but I want it in concentration levels. I've attached a snipet of the results I'm getting. I want the y-axis to be concentration rather than number density. Any help would be appreciated. 
![pu239](https://user-images.githubusercontent.com/77926205/105632807-18699f00-5e4d-11eb-8306-93692106e72b.png)

**Comment by paulromano** [comment]
Hi @hhhnain. The `ResultsList.get_atoms` function has an argument called `nuc_units` that can be set to "atom/b-cm" or "atom/cm3" (see documentation [here]()https://docs.openmc.org/en/stable/pythonapi/generated/openmc.deplete.ResultsList.html#openmc.deplete.ResultsList.get_atoms) so that you'd get a concentration rather than absolute number of atoms.

By the way, these types of questions are better suited for our [discourse forum](https://openmc.discourse.group/). We generally use issues on github for tracking bugs, feature requests, etc.

**Comment by hhhnain** [comment]
Thank you so much. Apologies for any inconvenience. I'm new to all this. I tried to look for an official page but was unable to find it. Again many thanks 👍On 25 Jan 2021 13:56, Paul Romano <notifications@github.com> wrote:
Hi @hhhnain. The ResultsList.get_atoms function has an argument called nuc_units that can be set to "atom/b-cm" or "atom/cm3" (see documentation here so that you'd get a concentration rather than absolute number of atoms.
By the way, these types of questions are better suited for our discourse forum. We generally use issues on github for tracking bugs, feature requests, etc.
