### ISSUE TITLE
Interpolation along incident energy in thermal scattering laws

### ISSUE THREAD

**Issue by HunterBelanger** [openmc-dev/openmc#1826]
Currently, when sampling from the `IncoherentInelasticAE` distribution, the outgoing data associated with the closest incident energy is always used. For other similar distributions, we typically perform stochastic interpolation, sampling between either the lower or higher incident energy, and then perform unit-based interpolation to obtain the final outgoing energy. This is also what our documentation states, and is how it used to be done back in the Fortran days with v0.10.0. Is there a reason that this is no longer done, or is this a bug in the current `IncoherentInelasticAE` implementation ? I tried looking in the MCNP theory manual for some insight as to how they treat the continuous energy representation, but they only mention the discrete energy representation.

**Comment by paulromano** [comment]
@HunterBelanger yes, the way the outgoing data is selected was changed in #1420 to match the treatment in MCNP. To be honest, I don't know why data is chosen for the closest incident energy instead of using stochastic interpolation, but that's how it's done in MCNP and, without a strong reason to do otherwise, we chose to match MCNP. You could ask the NJOY folks (@whaeck) about this and they more have insight as to how the data _should_ be used.
