### ISSUE TITLE
non-rectangular nor hexagonal lattice

### ISSUE THREAD

**Issue by Bugami** [openmc-dev/openmc#1903]
Hi everyone,

I have an issue to define a lattice for MTR fuel element which in some cases has a curved lattice. I tried to make the fuel cell as curved and it worked while I am trying to do a curved lattice which I couldn't find a suitable function for it because all the provided either rectangular or hexagonal.

Is there any function can do a curved lattice as shown in drawing below?
![WhatsApp Image 2021-11-03 at 11 41 18 AM](https://user-images.githubusercontent.com/86521023/140030476-cef11bf7-0c26-4fe3-9cad-6b4adf3b15c6.jpeg)

Thank you and looking for your support

**Comment by gridley** [comment]
Firstly, this can be modeled with a sqare lattice. Look at the center point of each unit cell, and notice that they are arranged such that (x_i, y_j) = (i delta x + x0, j delta y + y0). That is the definition of a square lattice. You'll just have to cut off the curved parts and put them into the adjacent cells.

Secondly, I'm closing this because it's not an issue with a code. If you would like user support for OpenMC, please use the discourse forum.

https://openmc.discourse.group/
