### ISSUE TITLE
location of h5 files with settings.output

### ISSUE THREAD

**Issue by shimwell** [openmc-dev/openmc#1996]
Hi all

@drjamesallison are making use of the nice feature that allows use to write output files to a folder
```
settings.output = {'path', '/home/myfolder'}
```

Just wondering what are peoples thoughts on writing more files to that folder

Currently these files are written to the specified folder
```
tracks.h5
statepoint.1.h5
```

However these files do not appear to be written to that folder
```
tallies.out
summary.h5
```

**Comment by paulromano** [comment]
That seems like an oversight. I think it's a reasonable expectation that all the files should go to the specified output folder. Are you interested in putting in a PR for that?

**Comment by shimwell** [comment]
I am keen to make a PR but I'm don't think my C++ is good enough for this. I had a quick peak at the source code

I think these two lines would need changing
https://github.com/openmc-dev/openmc/blob/062b8897ae232825ba6e3f5130f05bac4fc487ec/src/summary.cpp#L26
https://github.com/openmc-dev/openmc/blob/062b8897ae232825ba6e3f5130f05bac4fc487ec/src/output.cpp#L581

I had a look to see how the statepoint is written and how the filename is found.

So I think that summary.cpp should be changed to

```
  // Set filename for summary
  filename_ = fmt::format("{0}summary.h5", settings::path_output, w);

  // Create a new file using default properties.
  hid_t file = file_open(filename_, 'w');
```

I guess output.cpp should be changed to
```
  // Set filename for tallies_out
  filename_ = fmt::format("{0}tallies.out", settings::path_output, w);

  // Open the tallies.out file.
  std::ofstream tallies_out;
  tallies_out.open(filename_, std::ios::out | std::ios::trunc);
```

Does this look about right (trying to avoid a messy PR)

**Comment by paulromano** [comment]
@shimwell Yes that mostly looks good. You can use `{}` instead of `{0}` (as in Python, if you omit the index number it just does it by the order of the passed arguments). For the tallies.out one, I wouldn't use a trailing underscore in the variable `filename_`. Names with trailing underscores [indicate a class data member](https://docs.openmc.org/en/latest/devguide/styleguide.html#naming). If you just have a local variable, the naming convention is `lowercase_with_underscores`.

Also, don't worry if PRs take a few iterations :smile: we're happy to work with people to get things in the right shape, especially new contributors.
