### ISSUE TITLE
Use of depletion operator as context manager

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#2112]
@yardasol and I were discussing the `TransportOperator` class and how it is used as a context manager by the `Integrator` class:
https://github.com/openmc-dev/openmc/blob/b72c4593a328d9a16f6d3ab1285854527d4c1045/openmc/deplete/abc.py#L778

We both agree that the use of the context manager is not very clear. In fact, most of what the `__enter__` and `__exit__` method are doing is just moving to do a different directory, which doesn't have much to do with the operator at all. If we want to use a context manager, it should just handle moving between directories, and then the call to get the initial condition should be explicit in `Integrator.integrate()`, something like:
```Python
with change_directory(self.operator.output_dir):
    vec = self.operator.initial_condition()
    ...
```

One other point we talked about: the `AtomNumber` class uses the attribute name `n_nuc_burn` which is set to the number of nuclides in the depletion chain, but elsewhere we use "burnable nucs" to mean the intersection of the nuclides in the chain and those that actually have cross section data. To prevent confusion, it would be better to call that variable `n_nuc_chain`.

**Comment by yardasol** [comment]
I agree that the current way we are using the context manager is a bit opaque. However upon further reflection, I think that the attribute name `n_nuc_burn` is fine, since there is nothing about the `AtomNumber` class that has anything to do with the depletion chain (explicilty).

It may be useful to note that in the depletion example, the `_burnable_nuclides` and `chain` attribute of `operator` both have the same length.
