### ISSUE TITLE
Tracklength tally on spherical mesh is incorrect when mesh grid point and surface align

### ISSUE THREAD

**Issue by eepeterson** [openmc-dev/openmc#2369]
I think this is another manifestation of something similar to the issue described in #2065 and fixed in #2108. When you have radial mesh grid points that align with `Sphere` surfaces there is a spike in the corresponding tracklength flux tally at that point. The following MWE shows this:

```
import numpy as np
import matplotlib.pyplot as plt
import openmc


model = openmc.model.Model()

model.materials = openmc.Materials()
radii = [5, 50, 100, 150, 250]
spheres = [openmc.Sphere(r=ri) for ri in radii]
spheres[-1].boundary_type = 'vacuum'

regions = openmc.model.subdivide(spheres)[:-1]
cells = [openmc.Cell(region=r, fill=None) for r in regions]
geom = openmc.Geometry(cells)

model.geometry = geom

settings = openmc.Settings(run_mode='fixed source')
settings.batches = 100
settings.particles = 10000
src = openmc.Source()
src.space = openmc.stats.Point()
src.energy = openmc.stats.Discrete([14.06e6], [1])
settings.source = src
model.settings = settings

mesh = openmc.SphericalMesh()
mesh.r_grid = np.linspace(0, 250, 501)
mesh_filter = openmc.MeshFilter(mesh)

tally = openmc.Tally()
tally.scores = ['flux']
tally.filters = [mesh_filter]

model.tallies = openmc.Tallies([tally])

model.export_to_model_xml()
sp_filename = model.run()

sp = openmc.StatePoint(sp_filename)

nflux = sp.tallies[1]
mesh = nflux.find_filter(openmc.MeshFilter).mesh
r_grid = mesh.r_grid
r = (r_grid[1:] + r_grid[:-1])/2
volumes = np.diff(r_grid**3)*4/3*np.pi
neutron_flux = nflux.get_reshaped_data().squeeze()

fig, ax = plt.subplots()
ax.semilogy(r, neutron_flux / volumes, 'o')
ax.set_xlabel('Radius (cm)')
ax.set_ylabel('Flux (n/cm2/source)')
plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/18011007/215661444-18086a5d-92c4-478e-98bc-2c7b4403978c.png)

**Comment by pshriwise** [comment]
I think I've gotten to the bottom of this @eepeterson. 

The nature of the bug is somewhat subtle and has to do with the spherical surface intersection routine returning a very small distance to intersection (~ $1 \times 10^{-14}$ )for a surface just behind the particle.

The full situation is this: A particle track is stopped on a geometric boundary coincident with the boundary of one of the mesh surfaces. Let's say it's on the surface between bin 100 and 101 for this example.

![Untitled drawing](https://user-images.githubusercontent.com/4563941/223877334-a24253ce-8dfd-45bf-b7aa-216ea4cf5008.png)

The correct bin is selected for the particle by using a position just in front of the particle's true position (nudged forward by `TINY_BIT`), so the particle is established to be in bin 101, which is correct for our purposes.

According to the `SphericalMesh::distance_to_grid_boundary` method, the particle will be intersected with both the surface it's coincident with and the next surface along its direction (the outer spherical surface of bin 101) and use the minimum of those two intersection distances to tally the first segment of the track.

https://github.com/openmc-dev/openmc/blob/9768e34b869e9d698282778d2397bf9a982ed24f/src/mesh.cpp#L1407-L1410

In this case when the particle is coincident with the boundary, it can intersect with the coincident surface at a very small distance -- order $1 \times 10^{-14}$. This small distance should be negligible in terms of tally results, but what makes this really problematic is that the algorithm then thinks the next track should be tallied in bin 100.

Because we've now moved the particle forward this tiny bit, the intersection with the outer surface of bin 100 will be `INF`. The intersection with the inner surface of bin100 will also be `INF` because the particle certainly doesn't intersect that boundary. As a result, essentially the entirety of the particle's track will be tallied in bin 100. Not great.

I've implemented a solution in which we only check the surface ahead of the particle according to the bin it resides in. Meaning we wouldn't even consider an intersection with the coincident surface in this case because it isn't an "exiting" intersection from the element we consider the particle to be in. 

https://github.com/pshriwise/openmc/blob/e22e55656f08d2ec84e478d0adfb32f43f7cb7be/src/mesh.cpp#L1411-L1416

After implementing this fix, the jumps in the tally data no longer appeared.


![sphere_tally_fixed](https://user-images.githubusercontent.com/4563941/223878721-ef4470de-71cd-4a64-8b79-8528641d0a19.png)
