### ISSUE TITLE
Theory documentation on random number generation outdated

### ISSUE THREAD

**Issue by gridley** [openmc-dev/openmc#2486]
Just pointing out that the docs still talk about LCGs for random numbers in OpenMC, but the PCG generator is now used. It would be nice to eventually update this and briefly describe the PCG generator as an extra section in the theory guide, leaving the LCG documentation as introductory material.

**Comment by jtramm** [comment]
Great point -- it would be nice to add another section discussing what PCG is and what it adds to the LCG process, so that it's clear what OpenMC uses currently.

One interesting thing to note is that PCG actually still uses an LCG at its core, it just permutes the output bits rather than emitting the LCG state variable directly. The permutations improve the numerical quality of the PRNG as basic LCG's tend to have different amounts of randomness in low vs. high order bits, so the permutation step helps to mix the bits in.

**Comment by rzehumat** [comment]
Hi @gridley and @jtramm , would it be possible to volunteer on this issue? 

I am new to the project. As this is only documentation-related, I though it could be suitable for newcommers.
