### ISSUE TITLE
The meaning of "masking" components in a `Plot`

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#2503]
I was about to submit a pull request fixing what I thought was a "bug", namely that when you create a `Plot` object and ask it to mask certain components, e.g.
```Python
plot = openmc.Plot()
plot.mask_components = [cell1, cell2]
```
it will result in a plot that shows every cell other than `cell1` and `cell2`. I had assumed it was the other way around. However, once I saw the docstring about `mask_components` and `mask_background`:
https://github.com/openmc-dev/openmc/blob/4cadcbcf029310ced0eb3e7f638259f600335238/openmc/plots.py#L279-L282

I see that the wording in `mask_background` implies that things you list in `mask_components` are the only things you _will_ see, as opposed to the only things you _won't_ see. Is that confusing to anyone else or just me?

Tagging my plotting peeps: @pshriwise @shimwell @kkiesling

**Comment by shimwell** [comment]
That does sound confusing to me

**Comment by gridley** [comment]
I've always found this to be cryptic and have been afraid to touch it. So the purpose is to show only a few cells or materials at a time and automatically blank everything else out?

**Comment by paulromano** [comment]
@gridley Yes, that's what it would appear to be. To me that contradicts the notion of "masking a component", which I personally take to mean "don't show that component".

**Comment by kkiesling** [comment]
From a photo editing perspective this makes sense to me. I believe it's consistent with how the mask term is used elsewhere in the art world. If I mask `cell1`, then that means I want to hide `cell1` and protect it from anything else I do to the image. Therefore `mask_components` would be the list of components I want to mask and protect. So I'd see everything except the things I list there.

I think the `mask_background` provides an opportunity for reversal because sometimes it's easier to state what you want to see and ignore the rest. From the docstring though I am not sure why that would be an iterable instead of just a single value (or even just true/false). To me that's the only confusing part.

**Comment by paulromano** [comment]
@kkiesling 
> If I mask `cell1`, then that means I want to hide `cell1` ... So I'd see everything except the things I list there.

Right, and currently, you get the opposite — you only see the things that you _do_ list there.

`mask_background` specifies a color (hence an iterable of int like `(255, 0, 0)`) for any component that is masked. The name is indeed confusing.

**Comment by paulromano** [comment]
@kkiesling Make the following change to the pincell example in the repo:
```diff
diff --git a/examples/pincell/build_xml.py b/examples/pincell/build_xml.py
index c5d614ea9..04077c7ad 100644
--- a/examples/pincell/build_xml.py
+++ b/examples/pincell/build_xml.py
@@ -110,3 +110,8 @@ spectrum_tally.scores = ['flux']
 # Instantiate a Tallies collection and export to XML
 tallies = openmc.Tallies([mesh_tally, spectrum_tally])
 tallies.export_to_xml()
+
+plot = openmc.Plot.from_geometry(geometry)
+plot.mask_components = [fuel]
+plots = openmc.Plots([plot])
+plots.export_to_xml()
```
And then run `openmc --plot` and look at the resulting plot.

**Comment by kkiesling** [comment]
I see. Yes this seems like incorrect behavior based on the traditional definition of a mask.
