### ISSUE TITLE
Photon Transport benchmark against MCNP unsatisfactory

### ISSUE THREAD

**Issue by azimgivron** [openmc-dev/openmc#2545]
Hello, 

I have tried to benchmark the photon transport implemented in OpenMC against MCNP, with JEFF33 data. So I modeled two spheres, the inner most is in U235 and the outer most is made of air (N14 at 80% and O16 at 20%). Their respective radius are 8,5cm and 15cm. Both are centered on the same point. I also placed a cylinder in the sphere of air, at a distance of the center of 10.5cm. The cylinder has a radius of 2cm and a height of 5cm. The material it is made is Si28 at 50% and C0 (C12 in MCNP) at 50%. All materials are at 293.15K.

The image shows an "XZ" cut at Y=0.
![xy](https://github.com/openmc-dev/openmc/assets/27843989/db6415e9-c9f3-4a8b-ab37-6d8f7d854497)

I made a criticality calculation and measured the heat deposited by neutrons and photons on the cylinder. I also measured the flux discretized in 18 energy groups of neutrons and photons in the different parts/cells. I found significant differences in the photons flux and heat deposition. The figures below illustrates that issue.
![comparison](https://github.com/openmc-dev/openmc/assets/27843989/2af9d50f-f20f-4975-b83d-30bed7eeedda)
![photon_flux](https://github.com/openmc-dev/openmc/assets/27843989/ad55eae0-f560-44c9-bb90-7741adda11b2)

I provide you the zip containing the excel sheet used for post processing and the OpenMC code I implemented for that purpose in Jupyter notebook.

I do not know whether it is a bug in OpenMC or mis manipulation on my side but the neutron flux is similar while the photon one is not so I do not understand how it is possible (since the data used both cases is the same).

Any lead on that ?
[val.zip](https://github.com/openmc-dev/openmc/files/11643070/val.zip)

**Comment by gridley** [comment]
Sorry that it's not clear, but I think you should post this is the discourse (link below). The issues section on github is more for confirmed bugs in the code, and while this may be a bug, it is potentially also due to the input scripts at this point. Sorry I can't look into it more for you!

One note on your input though: the way you're defining materials is a little unusual. I'm not sure if inheriting from openmc.Material like that is going to give correct behavior. You might want to try defining them in the more conventional manner as seen in the example inputs.

Aside from that, this is likely a normalization problem. I think that your interpretation of the MCNP heating results are potentially incorrect. It may be reporting heating in terms of per source photon, not per source neutron, or something like that. MCNP is showing nearly a 50/50 split in photon vs. neutron heating, and that's just not how fission energy is distributed. The majority comes from fission, especially in a small leaky problem like this!

https://openmc.discourse.group/c/user-support/5
