### ISSUE TITLE
openmc filters are not subclasses of openmc.FilterMeta

### ISSUE THREAD

**Issue by akoen** [openmc-dev/openmc#2697]
## Bug Description

`tallies.py` checks that a list of filters is of type FilterMeta, but this never (seems to) evaluate to true as `Filter` only has `FilterMeta` as a metaclass, not a base class.

https://github.com/openmc-dev/openmc/blob/d4c40aa355de33f4f5bc14eb61ceb213b4d7d44f/openmc/tallies.py#L1103

## Steps to Reproduce

```bash
python -c "import openmc; print(issubclass(openmc.EnergyFilter, openmc.FilterMeta))" 
False
```
## Environment

```
OpenMC version 0.13.3
Git SHA1: 27cb0dc97960fe6d750eb5a93584a9a0ca532ac8
Copyright (c) 2011-2023 MIT, UChicago Argonne LLC, and contributors
MIT/X license at <https://docs.openmc.org/en/latest/license.html>
Build type:            RelWithDebInfo
Compiler ID:           AppleClang 14.0.3.14030022
```

**Comment by eepeterson** [comment]
Hi @akoen this is a little bit confusing so thanks for posting! `cv.check_type` will check if the objects in the `Iterable` `filters` are  instances of `openmc.FilterMeta` using `isinstance` rather than `issubclass`, which does successfully evaluate to `True`. This works because instances of a metaclasses are classes. Usually when you want to check if an object or class (which are objects themselves in Python) obeys a certain protocol or interface you will use `isinstance` instead of `issubclass`. Does this clear up your issue or is there some specific use case where `cv.check_type` is not doing what you expect it to be doing?

**Comment by eepeterson** [comment]
To demonstrate this a little more here are a couple examples:
```python
print(isinstance(openmc.EnergyFilter, openmc.FilterMeta))
True
print(isinstance(openmc.EnergyFilter([0, 20e6]), openmc.FilterMeta))
False
print(isinstance(openmc.EnergyFilter([0, 20e6]), openmc.EnergyFilter))
True
```

**Comment by akoen** [comment]
Apologies, I was dealing with an issue where this check was failing and I mistakenly attributed it to this, but it was a sneaky autoreload bug instead.
