### ISSUE TITLE
Chain file `stats` integral does not match decay constant

### ISSUE THREAD

**Issue by jbae11** [openmc-dev/openmc#2777]
## Bug Description

I don't think this is a bug necessarily, but it seems like getting the integral from the `source` in the chain file does not match the analytically calculated decay constant. Please see code below. The chain file used was from the website. Could this be a binning thing that happened while generating the chain file? I also checked the activity results between OpenMC and ORIGEN and did see that ORIGEN is consistent with the analytical solution (`np.log(2)/half_life_in_seconds`) and OpenMC was off by ~2%. 

And as always, if I'm missing something, feel free to yell at me and close the issue :) 

```
import openmc
from openmc.deplete import Chain
chain_file_path = '/home/4ib/Downloads/chain_endfb71_pwr.xml'
chain = Chain.from_xml(chain_file_path)
for nuc in chain.nuclides:
    if nuc.name == 'Ba137_m1':
        print(nuc.name)
        int_lambda = nuc.sources['photon'].integral()
        print(int_lambda)
        break
simple = np.log(2) / nuc.half_life
print(simple)
off_by = (simple - int_lambda) / simple
print(off_by * 1e2, '%')
```

**Comment by eepeterson** [comment]
This is because there is an `'electron'` source for Ba137_m1. If you look in the chain file there is likely a second source so if you do `nuc.sources['photon'].integral() + nuc.sources['electron'].integral()` you should recoup those few percent I think.

**Comment by jbae11** [comment]
ohh it looks like that shoots it off to be higher than the analytical solution:
```
        int_lambda = nuc.sources['photon'].integral() + nuc.sources['electron'].integral()
->
0.0052893686753903045
relative_error -16.845%
```

**Comment by paulromano** [comment]
This doesn't have to do with electrons actually. This is a result of the data in the decay evaluation itself. Namely, each spectral line for a gamma/x-ray in the decay evaluation is listed with an intensity. If you sum up the intensities of all x-ray / gamma lines, you get 0.9811 instead of 1.0. So this is why if you integrate the photon distribution, it's 2% less than the overall activity -- because the decay evaluation itself is saying that for every decay, you get 0.9811 photons. If you believe that every decay should produce 1 photon, that is an issue you would have to take up with the nuclear data evaluators. Either way, integrating the  source spectrum is probably not the best way of determining activity.

Also, just a tip -- your variable `simple` could have been defined as `nuc.decay_constant` :smile:

**Comment by jbae11** [comment]
completely understanding nuclear data will be an eternally elusive goal for me haha

thanks for the wisdom @paulromano !
