### ISSUE TITLE
Tallies ignored or not output in depletion calculations

### ISSUE THREAD

**Issue by gridley** [openmc-dev/openmc#2839]
## Bug Description
The expected behavior of OpenMC when run via the `CoupledOperator` for depletion is to output the tallies from the beginning of each time step in files named `openmc_simulation_n{i}.h5` where i is the time step. However, NO tallies are ever present.

## Steps to Reproduce

Go to the classic pincell_depletion problem, and modify the steps leading to the time integration to read as:

```
tallies = openmc.Tallies()
abs_235 = openmc.Tally()
abs_235.name = 'U235 absorption'
abs_235.nuclides = ['U235']
abs_235.scores = ['absorption']
tallies.append(abs_235)

model = openmc.Model(geometry=geometry, settings=settings, tallies=tallies)

```

You're in for a big disappointment if you want to check the absorption fraction into U235 at timestep 2 though, because:

```
In [1]: import openmc

In [2]: sp = openmc.StatePoint('./openmc_simulation_n2.h5')

In [3]: sp.tallies
Out[3]: {}
```

😢 

## Environment

Arch linux, latest commit.

**Comment by pshriwise** [comment]
The depletion `Tally.writeable` property is marked `False` on creation by one of the helper classes and as a result aren't written to the statepoint file. That's why you won't find them in the resulting `.h5` file. When you say the expected behavior is to find the tallies in that file, is that stated in the documentation somewhere? We should clarify this if so.

At any rate, I have an application where I'd like the tally results to appear in the statepoint file for a case where I'm using an external executable (Cardinal) as a method for generating my statepoint file in place of OpenMC, but I need the tally results in that statepoint file so I can get them into the depletion module to do the Bateman solve and pass updated material compositions back to Cardinal.

**Comment by gridley** [comment]
Ah no, sorry, I wasn't talking about the depletion reaction rates.

What I'm talking about is user-defined tallies. They're not appearing, even if they're marked as writeable. It turned out in the PR that fixes this that the `tallies.xml` wasn't being exported by the model when passing it to a `CoupledOperator`.

**Comment by pshriwise** [comment]
Ah, I see. Thought that was a separate issue. My bad!
